let smsFields = new Map();
smsFields.set("analysis_type", "Type of analysis at external lab")
smsFields.set("container_id", "Identifier of the multi-well storage box or plate containing the sample")
smsFields.set("container_mass", "Mass of the sample within the container in grams")
smsFields.set("fate", "Fate of a sample")
smsFields.set("filter_volume", "Volume of material passed through filter")
smsFields.set("sample_mass","Mass of the sample in grams")
smsFields.set("num_containers","Number of vials or containers associated with a sampleID")
smsFields.set("preservative_concentration", "Concentration of preservative used in the sample")
smsFields.set("preservative_type","Type of preservative used in the sample")
smsFields.set("preservative_volume","Volume of preservative used in the sample")
smsFields.set("remarks","Associated remarks field")
smsFields.set("sample_code","Barcode of a sample")
smsFields.set("sample_condition","Condition of a sample")
smsFields.set("sample_tag","Identifier for sample")
smsFields.set("sample_type","Type of sample")
smsFields.set("sample_volume","Volume of the sample")
smsFields.set("shipment_condition","The condition in which the shipment was received")
smsFields.set("specimen_count","Number of individuals in the container")
smsFields.set("temperature","Temperature of the cooler when the sample arrived at the external lab")
smsFields.set("well_coordinate","Location of sample in multi-well storage box or plate")
smsFields.set("guid","Global Unique Identifier")
smsFields.set("fate_date","Transaction date of a fate update for a sample")
smsFields.set("fate_location","Transaction location of a fate location update for a sample")

export default smsFields;
