enum AppActions {
  FETCH_PRODUCTS = 'FETCH_PRODUCTS',
  FETCH_PRODUCTS_WORKING = 'FETCH_PRODUCTS_WORKING',
  FETCH_PRODUCTS_COMPLETED = 'FETCH_PRODUCTS_COMPLETED',
  FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR',
  RESET_FETCH_PRODUCTS = 'RESET_FETCH_PRODUCTS',
}

export default AppActions;
